### ISSUE TITLE
Dependency that is not mentioned in docs

### ISSUE THREAD

**Issue by LigasN** [STMicroelectronics/ov2640#1]
https://github.com/STMicroelectronics/stm32-ov2640/blob/05cbd9248ad3dad90f89d3ffc3acf55f3c5d2b4d/ov2640.h#L48

Hi 🙂 
Why there is some included file, which is not mentioned anywhere? There should be a comment at least explaining why is it here and not in the repository.

**Comment by ALABSTM** [comment]
Hi @LigasN,

Actually, this repository is not intended to be used standalone. In the [compatibility info](https://github.com/STMicroelectronics/stm32-ov2640/blob/main/README.md#compatibility-information) section of the **README.md** file, it is mentioned that a _"consistent set of versions"_ shall be used.

Actually, this repository shall be used along with the [stm32-bsp-common](https://github.com/STMicroelectronics/stm32-bsp-common) repository. In this latter, you can find the [camera.h](https://github.com/STMicroelectronics/stm32-bsp-common/blob/main/camera.h) file included at line 48.

More generally, this repo and other similar ones (complete list [here](https://github.com/STMicroelectronics/STM32Cube_MCU_Overall_Offer/blob/master/README.md#stm32cube-bsp-components-drivers)) are intended to be integrated in a file structure similar to the one found in the STM32Cube firmware ([example](https://github.com/STMicroelectronics/STM32CubeF4/tree/master/Drivers/BSP/Components)) in order to be properly used.

I hope this answers your question. Please allow me to close this issue.

With regards,

**Comment by LigasN** [comment]
That would be awesome to have that information on the bottom of readme. Anyways, thank you for the answer.

Best regards,
Norbert
